data_path: data/Project1140.csv
end_date: '2024-09-28'
epoch_params:
  high: 80
  low: 50
epochs: 40
future_hours: 24
model: Transformer
model_complexity: low
model_params:
  high:
    d_model: 128
    dropout: 0.3
    hidden_dim: 64
    num_heads: 8
    num_layers: 6
  low:
    d_model: 32
    dropout: 0.1
    hidden_dim: 16
    num_heads: 2
    num_layers: 2
past_days: 3
past_hours: 72
plot_days: 7
save_dir: temp_results/1140/Transformer_low_PV_plus_HW_72h_TE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  batch_size: 64
  learning_rate: 0.001
train_ratio: 0.75
use_forecast: false
use_hist_weather: true
use_pv: true
use_time_encoding: true
val_ratio: 0.15
weather_category: all_weather
