# ========================================
# Plant Configuration Template
# ========================================
# Copy this file for each plant and modify the following parameters

# Plant Basic Information
plant_id: "1140"  # Plant ID (required)
plant_name: "Project 1140"  # Plant name (optional)

# Data File Path (required)
data_path: "data/Project1140.csv"

# Data Time Range (modify according to actual data)
start_date: "2022-01-01"
end_date: "2024-09-28"

# Forecast Horizon
future_hours: 24

# Data Split Ratio (shuffle split is used when shuffle_split: true)
train_ratio: 0.8  # 80% of data
val_ratio: 0.1    # 10% of data
test_ratio: 0.1   # 10% of data

# Weather Feature Category (adjust based on data availability)
weather_category: "all_weather"  # Options: "all_weather", "irradiance", "temperature", "none"

# Support Ideal NWP (set based on data availability)
has_ideal_nwp: true  # Set to true if actual weather data is available

# Results Save Directory (plant ID will be auto-added)
results_base_dir: "results"

# ========================================
# Model Hyperparameters (general, usually no need to modify)
# ========================================

# Deep Learning Model Parameters
dl_params:
  low:
    epochs: 20
    batch_size: 64
    learning_rate: 0.001
    patience: 10
    min_delta: 0.001
    weight_decay: 0.0001
    # Model architecture parameters
    d_model: 16
    hidden_dim: 8
    num_heads: 2
    num_layers: 1
    dropout: 0.1
    # TCN specific parameters
    tcn_channels: [8, 16]
    kernel_size: 3
  
  high:
    epochs: 50
    batch_size: 64
    learning_rate: 0.001
    patience: 10
    min_delta: 0.001
    weight_decay: 0.0001
    # Model architecture parameters
    d_model: 32
    hidden_dim: 16
    num_heads: 2
    num_layers: 2
    dropout: 0.1
    # TCN specific parameters
    tcn_channels: [16, 32]
    kernel_size: 3

# Machine Learning Model Parameters - validated optimal config
ml_params:
  low:
    n_estimators: 10
    max_depth: 1
    learning_rate: 0.2
    random_state: 42
    verbosity: -1  # Silent mode: suppress warnings
  
  high:
    n_estimators: 30
    max_depth: 3
    learning_rate: 0.1
    random_state: 42
    verbosity: -1  # Silent mode: suppress warnings

# Linear Model Parameters (no hyperparameters)
linear_params: {}

# ========================================
# Save Options (adjust as needed)
# ========================================
save_options:
  save_model: false  # Whether to save trained models
  save_predictions: false  # Whether to save predictions
  save_training_log: false  # Whether to save training log
  save_excel_results: false  # Whether to save Excel results (recommended off for 284 experiments)